//Auth types
export const AUTH_LOGIN_USER = 'AUTH_LOGIN_USER';
export const AUTH_LOGIN_USER_FAIL = 'AUTH_LOGIN_USER_FAIL';
export const AUTH_LOGIN_USER_SUCCESS = 'AUTH_LOGIN_USER_SUCCESS';
export const AUTH_CREATE_USER = 'AUTH_CREATE_USER';
export const AUTH_CREATE_USER_FAIL = 'AUTH_CREATE_USER_FAIL';
export const AUTH_CREATE_USER_SUCCESS = 'AUTH_CREATE_USER_SUCCESS';
